export const surpriseMePrompts = [
    'a graffiti in the style of Banksy featuring nintendo characters',
    'a historic castle nestled in a lush, green forest',
    'a majestic lion resting under a tree with a natural crown of flowers',
    'a futuristic cityscape featuring innovative architecture and green spaces',
    'a serene forest illuminated by natural light filtering through the trees',
    'an ancient book with intricate illustrations that seem to move',
    'a moody photograph of a fog-covered Norwegian landscape',
    'a serene underwater scene showcasing vibrant coral reefs and marine life',
    'a dragon peacefully resting in a cozy cave surrounded by treasures',
    'a lifelike close-up of a person with short hair, surrounded by deep blue water',
    'a serene mountain landscape with a crystal-clear lake reflecting the peaks',
    'a steampunk airship sailing gracefully through the sky',
    'a futuristic space station adorned with vibrant alien flora',
    'a charming bakery with a classic design and artisanal pastries',
    'a bustling city with towering skyscrapers and modern architecture',
    'a mythical phoenix rising majestically from the ashes',
    'a cozy woodland cottage with a picturesque thatched roof',
    'a futuristic robot chef expertly preparing a gourmet meal',
    'a tranquil Japanese garden featuring a koi pond and cherry blossoms',
    'an alien invasion depicted in the nostalgic style of 1950s art',
    'a contemporary museum in Paris, showcasing modern art',
    'a futuristic city park filled with innovative sculptures',
    'a photograph of a woman with long braids wearing headphones',
    'a vintage carousel with beautifully crafted horses and soft lights',
    'a playful puppy frolicking in a field of wildflowers',
    'a bustling market street in a colorful Mediterranean town',
    'a serene beach scene with a hammock swaying between palm trees',
    'a retro diner illuminated by neon signs, with classic cars parked outside',
    'a nostalgic old photograph capturing a moment in time',
    'a lively futuristic market filled with diverse alien species',
    'a serene forest path dappled with sunlight filtering through the trees',
    'a cozy study filled with ancient books and vintage furniture',
    'a futuristic laboratory with advanced technology and glowing test tubes',
    'an oil painting of a medieval European woman, wearing armor and giving a thumbs up',
    'a cozy winter cabin with a warm, roaring fireplace',
    'a serene meadow with a rainbow arcing over grazing animals',
    'a bustling urban street lined with towering skyscrapers',
    'a futuristic sports car speeding through a neon-lit city at night',
    'a serene waterfall cascading in a lush tropical jungle',
    'a busy spaceport filled with spaceships and a variety of alien beings',
    'an architectural photograph of a wooden house interior adorned with tropical plants',
    'a futuristic nightclub featuring laser lights and holographic displays',
    'a serene desert landscape with vast, towering sand dunes',
    'a bustling harbor with colorful fishing boats docked along the pier',
    'a magical starlit sky with clear constellations and shooting stars',
    'a modern amusement park with well-designed rides and attractions',
    'a futuristic skyscraper with a beautiful rooftop garden',
    'a serene island paradise with crystal-clear water and pristine white sand beaches'
];
