export const surpriseMePrompts = [
    'a vintage typewriter with floating holographic letters',
    'a whimsical fairy tale castle made of candy',
    'a majestic lion wearing a crown of flowers',
    'a futuristic cityscape with flying cars and neon lights',
    'a mystical forest with glowing mushrooms and fairies',
    'an enchanted book with illustrations coming to life',
    'a robot gardener tending to a lush rooftop garden',
    'a serene underwater scene with colorful coral and fish',
    'a dragon curled up with a treasure hoard in a cozy cave',
    'a magical library with floating books and a spiral staircase',
    'a serene mountain landscape with a crystal-clear lake',
    'a steampunk airship sailing through the clouds',
    'a futuristic space station with vibrant alien plants',
    'a whimsical bakery with talking pastries and sweets',
    'a cyberpunk city with towering skyscrapers and neon signs',
    'a mythical phoenix rising from the ashes',
    'a cozy woodland cottage with a thatched roof',
    'a futuristic robot chef preparing a gourmet meal',
    'a serene Japanese garden with a koi pond and cherry blossoms',
    'a magical tea party with enchanted creatures',
    'a whimsical hot air balloon festival in the sky',
    'a futuristic city park with holographic sculptures',
    'a celestial galaxy with swirling stars and planets',
    'a vintage carousel with ornate horses and lights',
    'a playful puppy in a field of wildflowers',
    'a bustling market street in a colorful Mediterranean town',
    'a serene beach scene with a hammock and palm trees',
    'a retro diner with neon signs and classic cars',
    'a magical unicorn prancing in a moonlit meadow',
    'a bustling futuristic market with diverse alien species',
    'a serene forest path with dappled sunlight',
    'a vintage circus with acrobats and clowns',
    'a mysterious wizard study filled with ancient books and potions',
    'a futuristic laboratory with glowing test tubes and gadgets',
    'a whimsical toy shop with animated toys',
    'a cozy winter cabin with a roaring fireplace',
    'a serene meadow with a rainbow and grazing animals',
    'a bustling urban street with towering skyscrapers',
    'a magical garden with oversized flowers and butterflies',
    'a futuristic sports car racing through a neon-lit city',
    'a serene waterfall in a lush tropical jungle',
    'a bustling spaceport with spaceships and aliens',
    'a vintage train station with steam engines and travelers',
    'a futuristic nightclub with laser lights and holograms',
    'a serene desert landscape with towering sand dunes',
    'a bustling harbor with colorful fishing boats',
    'a magical starlit sky with constellations and shooting stars',
    'a whimsical amusement park with animated rides',
    'a futuristic skyscraper with a rooftop garden',
    'a serene island paradise with crystal-clear water and white sand beaches'
];